#!/bin/sh

cd ${0%/*} || exit 1

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

# Unpack tables
tar -xf constant/Tables.tar -C constant

runApplication "$application"
